name: Run Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.COVERALL_SECRET }}
