name: Build & Test code on PR / push
on: [pull_request, push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build application
        run: ./gradlew build

      - name: Test application
        run: ./gradlew test

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: jacoco-report
          path: build/reports/jacoco/
          if-no-files-found: warn